general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "GeistMono Nerd Font" }
bold = { family = "GeistMono Nerd Font", style = "Ultra-Bold" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
bold_italic = { family = "GeistMono Nerd Font", style = "Bold Italic" }
size = 11

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 1.0

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" },
]

[terminal]
osc52 = "CopyPaste"
