
# ========= Border =========
file_panel_border = '#d4be98'
sidebar_border = '#d4be98'
footer_border = '#d4be98'

# ========= Border Active =========
file_panel_border_active = '#7daea3'
sidebar_border_active = '#7daea3'
footer_border_active = '#7daea3'
modal_border_active = '#7daea3'

# ========= Background (bg) =========
full_screen_bg = '#282828'
file_panel_bg = '#282828'
sidebar_bg = '#282828'
footer_bg = '#282828'
modal_bg = '#282828'

# ========= Foreground (fg) =========
full_screen_fg = '#d4be98'
file_panel_fg = '#d4be98'
sidebar_fg = '#d4be98'
footer_fg = '#d4be98'
modal_fg = '#d4be98'

# ========= Special Color =========
cursor = '#d4be98'
correct = '#a9b665'
error = '#ea6962'
hint = '#89b482'
cancel = '#ea6962'
gradient_color = ['#3c3836', "#3c3836"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#3c3836'
file_panel_top_path = '#3c3836'
file_panel_item_selected_fg = '#3c3836'
file_panel_item_selected_bg = '#282828'

# ========= Sidebar Special Items =========
sidebar_title = '#d4be98'
sidebar_item_selected_fg = '#3c3836'
sidebar_item_selected_bg = '#282828'
sidebar_divider = '#d4be98'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#ea6962'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#a9b665'
