exec-once = nwg-dock-hyprland -i 48 -nolauncher -mb 10 -mt 2 -w 15 -d -hd 0 -hdd 20
# exec-once = nwg-dock-hyprland -i 40 -nolauncher -ml 7 -p "left" -hl "overlay" -d
exec-once = hyprpm reload
exec-once = vicinae server
