source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    grace = 1
    fractional_scaling = 2
    immediate_render = false
    screencopy_mode = 0
}

bezier = smoothFade, 0.25, 1, 0.5, 1
animation = fade, 1, 5, smoothFade

background {
    monitor =
    path = ~/.config/omarchy/current/background
    color = $color
    blur_size = 3
    blur_passes = 4
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.6000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $font_color
    font_size = 112
    font_family = Geist
    shadow_passes = 0
    shadow_size = 0
    position = 0, 220
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $font_color
    font_size = 112
    font_family = Geist
    shadow_passes = 0
    shadow_size = 0
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:18000000] echo "<b><big> "$(date +'%A')" </big></b>"
    color = $font_color
    font_size = 18
    font_family = Geist
    position = 0, -15
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%d %b')" </b>"
    color = $font_color
    font_size = 14
    font_family = Geist
    position = 0, -40
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 1
    dots_size = 0.26
    dots_spacing = 0.64
    dots_center = true
    dots_rouding = -1
    rounding = 22
    outer_color = $check_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = true
    placeholder_text = 
    position = 0, 240
    halign = center
    valign = bottom
}

label {
    monitor =
    text = 
    color = $outer_color
    font_size = 14
    font_family = Geist
    shadow_passes = 0
    position = 0, -110
    halign = center
}

shape {
    monitor =
    color = $font_color
    size = 200, 5
    rounding = 99
    position = 0, 10
    halign = center
}

# label {
#     text =
#     color = $font_color
#     font_size = 10
#     font_family = Geist
#     position = 0, -190
#     halign = center
# }
