input {
    kb_options = caps:swapescape,compose:menu

    repeat_rate = 40
    repeat_delay = 600

    numlock_by_default = true
    sensitivity = 0.30

    touchpad {
        clickfinger_behavior = true
        scroll_factor = 0.4
        disable_while_typing = true
    }
}

windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
