# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    resize_on_border = true
    layout = dwindle
    hover_icon_on_border = true
    border_size = 0
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 6
    rounding_power = 10
    active_opacity = 1
    inactive_opacity = 0.90


    shadow {
        enabled = false 
      }

    blur {
        enabled = true
        size = 5
        passes = 2
        ignore_opacity =true
        xray = false
        new_optimizations = true
        contrast = 2
        popups = true

      }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = true
    animation = workspaces, 1, 2, default, slide
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
