windowrule {
    name = all-opaque-no-blur
    match:class = .*
    opaque = on
    no_blur = on
    opacity = 1.0 override 1.0 override
}
#
# windowrule {
#     name = zen-blur-chrome-only
#     match:class = ^(zen)$
#     opacity = 1.0 override 1.0 override
#     opaque = on
#     no_blur = off
# }

# windowrule = workspace 10 silent, match:title (Spotify Premium)
# windowrule = tile on, match:title (Spotify Premium)

# windowrule = workspace 11 silent, match:class (vesktop)
# windowrule = tile on, match:class (vesktop)

# windowrule = workspace 12 silent, match:class (obsidian)
# windowrule = tile on, match:class (obsidian)

# windowrule = float on, match:class (org.omarchy.gazelle)

windowrule {
    name = scratchpad-blur
    match:workspace = special:scratchpad
    no_blur = off
}

windowrule {
    name = tile-localsend
    match:class = ^(localsend)$
    float = off
    tile = on
}

layerrule {
    name = hyprlock-no-anim
    match:namespace = hyprlock
    no_anim = on
}

layerrule {
    name = dock-animation
    match:namespace = nwg-dock
    animation = popin 80%
}

layerrule {
    name = vicinae-animation
    match:namespace = vicinae
    animation = popin 80%
}
