include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family      Google Sans Code NF
bold_font        Google Sans Code NF Bold
italic_font      Google Sans Code NF Italic
bold_italic_font Google Sans Code NF Bold Italic
font_size        11.5

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations no
show_window_resize_notification no
confirm_os_window_close 0
enabled_layouts grid

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access (disabled for performance)
single_instance yes
allow_remote_control no

# Aesthetics
background_opacity 0.8
cursor_shape block
enable_audio_bell no
active_border_color #808080
url_style single
cursor_trail_color #879A39
cursor #879A39

# Performance optimizations
input_delay 0
repaint_delay 2
sync_to_monitor no
cursor_trail 1

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               separator
tab_separator               " ┇ "
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
disable_ligatures           never
