include ~/.config/omarchy/current/theme/kitty.conf

# Font
font_family CaskaydiaMono Nerd Font
bold_italic_font auto
font_size        8.7

# Window
window_padding_width 14
window_padding_height 14
hide_window_decorations no
show_window_resize_notification no
confirm_os_window_close 0
enabled_layouts grid

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access (disabled for performance)
single_instance yes
allow_remote_control no

# Aesthetics
cursor_shape block
enable_audio_bell no
active_border_color #808080

# Performance optimizations
input_delay 0
repaint_delay 2
sync_to_monitor yes

cursor_trail 75

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               separator
tab_separator               " ┇ "
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
